### PR TITLE
Add common abbreviations to timezone names

### PR DESCRIPTION
**Pull request by ndye**
I added some common abbreviations to the UTC offsets for the common folk who have no clue what "UTC-3:00" means. I also rearranged the README but that was just because I was bored. Let me know what you think I should change for the abbreviations because some of them are not the best choice I am sure.

### CODE REVIEW

**Comment by Eeems** [comment]
I would suggest that you added the newlines back to the ends of all the files you removed them from. Lots of tools assume that files end with newlines.

**Comment by ndye** [comment]
Nice catch, Atom still shows I have them so I didn't notice. I'll do that.

**Comment by ndye** [comment]
I am going to close this and open a new one because of an error in my setup that caused the bot to pull in new changes

**Comment by ndye** [comment]
Never mind, I am stupid.

**Comment by Eeems** [comment]
@ndye It looks like you made a number of changes to README.md? I'm guessing those were unintentional based on the merge?

**Comment by ndye** [comment]
Actually those were part of the original PR, I just checked and it looks like it is the same it was before the accidental merge. I made some changes to it mostly because of the flow of the document but its up to @calc84maniac they are just my personal preference.

**Comment by Eeems** [comment]
Ah, my bad. I didn't notice that in the original comment. I'd suggest separating that out into it's own PR. That way @calc84maniac can take the abbreviation changes without the Readme changes if he wants

**Comment by ndye** [comment]
I'm just going to close this and reopen it when I have figured out the proper way to set it up without the stupid bot.

**Pull request closed without merging**
